"use client";

import React, { useState, useMemo } from "react";
import { useRouter } from "next/navigation";
import {
  Breadcrumb,
  FormCard,
  FormInput,
  FormSelect,
  FormSearchableSelect,
  FormActionBar,
} from "@/components/ui";
import {
  useCategories,
  useSubCategories,
  useMaterials,
} from "@/features/attributes/hooks/use-attributes";
import { useMasterProductMutations } from "@/features/products/hooks/use-master-products";
import { categoryData } from "@/lib/mock-data/attributes/category.mock";
import { subCategoryData } from "@/lib/mock-data/attributes/sub-category.mock";
import { materialData } from "@/lib/mock-data/attributes/material.mock";

export default function NewMasterFGProductPage() {
  const router = useRouter();
  const { createMut } = useMasterProductMutations();

  // Fetch attribute options with mock data fallbacks
  const { data: serverCategories } = useCategories();
  const { data: serverSubCategories } = useSubCategories();
  const { data: serverMaterials } = useMaterials();

  const [formState, setFormState] = useState({
    name: "",
    categoryId: "",
    subCategoryId: "",
    materialId: "",
  });

  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitFeedback, setSubmitFeedback] = useState<{
    type: "success" | "error";
    message: string;
  } | null>(null);

  // Category options
  const categoryOptions = useMemo(() => {
    const list =
      serverCategories && serverCategories.length > 0
        ? serverCategories
        : categoryData;
    return list.map((c) => ({
      label: c.name,
      value: String(c.id),
    }));
  }, [serverCategories]);

  // SubCategory options (filtered by selected category)
  const subCategoryOptions = useMemo(() => {
    const list =
      serverSubCategories && serverSubCategories.length > 0
        ? serverSubCategories
        : subCategoryData;

    const filtered = formState.categoryId
      ? list.filter(
          (sc: any) =>
            String(sc.categoryId) === String(formState.categoryId) ||
            String(sc.category?.id) === String(formState.categoryId)
        )
      : list;

    return filtered.map((sc: any) => ({
      label: sc.name,
      value: String(sc.id),
    }));
  }, [serverSubCategories, formState.categoryId]);

  // Material options
  const materialOptions = useMemo(() => {
    const list =
      serverMaterials && serverMaterials.length > 0
        ? serverMaterials
        : materialData;
    return list.map((m) => ({
      label: m.name,
      value: String(m.id),
    }));
  }, [serverMaterials]);

  // Derived SKU (Auto-generated by Name + Category)
  const autoSku = useMemo(() => {
    const namePart = formState.name
      ? formState.name
          .trim()
          .toUpperCase()
          .replace(/[^A-Z0-9]+/g, "-")
          .replace(/^-|-$/g, "")
      : "";

    const selectedCategory = serverCategories?.find(
      (c) => String(c.id) === formState.categoryId
    );
    const categoryPart = selectedCategory?.name
      ? selectedCategory.name
          .trim()
          .toUpperCase()
          .replace(/[^A-Z0-9]+/g, "-")
          .replace(/^-|-$/g, "")
      : "";

    if (namePart && categoryPart) {
      return `${namePart}-${categoryPart}`;
    }
    if (namePart) {
      return namePart;
    }
    return "";
  }, [formState.name, formState.categoryId, serverCategories]);

  const handleChange = (field: string, value: string) => {
    if (field === "categoryId") {
      setFormState((prev) => ({ ...prev, categoryId: value, subCategoryId: "" }));
    } else {
      setFormState((prev) => ({ ...prev, [field]: value }));
    }
    if (errors[field]) {
      setErrors((prev) => {
        const updated = { ...prev };
        delete updated[field];
        return updated;
      });
    }
    if (submitFeedback) {
      setSubmitFeedback(null);
    }
  };

  const handleReset = () => {
    setFormState({
      name: "",
      categoryId: "",
      subCategoryId: "",
      materialId: "",
    });
    setErrors({});
    setSubmitFeedback(null);
  };

  const validate = () => {
    const newErrors: Record<string, string> = {};
    if (!formState.name.trim()) {
      newErrors.name = "Master Good Name is required";
    }
    if (!formState.categoryId) {
      newErrors.categoryId = "Category is required";
    }
    if (!formState.subCategoryId) {
      newErrors.subCategoryId = "Sub Category is required";
    }
    if (!formState.materialId) {
      newErrors.materialId = "Material is required";
    }
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async () => {
    if (!validate()) return;

    try {
      await createMut.mutateAsync({
        name: formState.name.trim(),
        sku: autoSku || `${formState.name.trim().toUpperCase().replace(/\s+/g, "-")}-FG`,
        categoryId: formState.categoryId,
        subCategoryId: formState.subCategoryId,
        materialId: formState.materialId,
      });

      setSubmitFeedback({
        type: "success",
        message: "Master Finished Good created successfully! Redirecting...",
      });

      setTimeout(() => {
        router.push("/products/master-fg-product");
      }, 1000);
    } catch (error: any) {
      const errMsg =
        (Array.isArray(error?.response?.data?.message)
          ? error.response.data.message.join(", ")
          : error?.response?.data?.message) ||
        error?.message ||
        "Failed to create Master Product. Please try again.";

      setSubmitFeedback({
        type: "error",
        message: errMsg,
      });
    }
  };

  return (
    <div className="space-y-6">
      {/* ── Breadcrumb Bar ── */}
      <Breadcrumb
        title="Product"
        items={[
          { label: "Product", href: "/products/master-fg-product" },
          { label: "Master Finished Good", href: "/products/master-fg-product" },
          { label: "New" },
        ]}
      />

      {/* Feedback Banner */}
      {submitFeedback && (
        <div
          className={`p-4 rounded-xl text-sm font-medium transition-all ${
            submitFeedback.type === "success"
              ? "bg-emerald-50 text-emerald-800 border border-emerald-200"
              : "bg-rose-50 text-rose-800 border border-rose-200"
          }`}
        >
          {submitFeedback.message}
        </div>
      )}

      {/* ── Master Finished Good Information Card ── */}
      <FormCard title="Master Finished Good Information">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Row 1, Col 1: Master Good Name * */}
          <FormInput
            label="Master Good Name"
            required
            placeholder="Enter product name"
            value={formState.name}
            onChange={(e) => handleChange("name", e.target.value)}
            error={errors.name}
          />

          {/* Row 1, Col 2: SKU (Auto) */}
          <FormInput
            label="SKU (Auto)"
            placeholder="Auto-generated by Name + Category"
            value={autoSku}
            disabled
            className="bg-slate-50/80 text-slate-600 cursor-not-allowed"
          />

          {/* Row 2, Col 1: Category */}
          <FormSelect
            label="Category"
            required
            chevronType="updown"
            placeholder="Select category"
            value={formState.categoryId}
            onChange={(e) => handleChange("categoryId", e.target.value)}
            options={categoryOptions}
            error={errors.categoryId}
          />

          {/* Row 2, Col 2: Sub Category */}
          <FormSelect
            label="Sub Category"
            required
            chevronType="updown"
            placeholder={formState.categoryId ? "Select sub category" : "Select category first"}
            value={formState.subCategoryId}
            onChange={(e) => handleChange("subCategoryId", e.target.value)}
            options={subCategoryOptions}
            error={errors.subCategoryId}
            disabled={!formState.categoryId}
          />

          {/* Row 3, Col 1: Material * */}
          <FormSearchableSelect
            label="Material"
            required
            placeholder="Search and select material..."
            value={formState.materialId}
            onChange={(val) => handleChange("materialId", val)}
            options={materialOptions}
            error={errors.materialId}
          />
        </div>
      </FormCard>

      {/* ── Form Action Bar ── */}
      <FormActionBar
        onCancel={() => router.push("/products/master-fg-product")}
        onReset={handleReset}
        onCreate={handleSubmit}
        isLoading={createMut.isPending}
        cancelLabel="Cancel"
        resetLabel="Reset"
        submitLabel="Create"
      />
    </div>
  );
}

